In [17]:
from utils import make_BCH2014_data
from scipy.linalg import toeplitz

import numpy as np

# Considering design 1a) and wide data
theta = 0.5
n_obs=10
dim_x = 25
rho = 0.5
R2_d = 0.5
R2_y = 0.5
random_seed=1312

v = np.random.standard_normal(size=[n_obs,])
zeta = np.random.standard_normal(size=[n_obs,])

toeplitz_list = [np.power(rho, k) for k in range(dim_x)]
toeplitz_list

[1.0,
 0.5,
 0.25,
 0.125,
 0.0625,
 0.03125,
 0.015625,
 0.0078125,
 0.00390625,
 0.001953125,
 0.0009765625,
 0.00048828125,
 0.000244140625,
 0.0001220703125,
 6.103515625e-05,
 3.0517578125e-05,
 1.52587890625e-05,
 7.62939453125e-06,
 3.814697265625e-06,
 1.9073486328125e-06,
 9.5367431640625e-07,
 4.76837158203125e-07,
 2.384185791015625e-07,
 1.1920928955078125e-07,
 5.960464477539063e-08]

In [18]:
cov_mat = toeplitz(toeplitz_list)
cov_mat

array([[1.00000000e+00, 5.00000000e-01, 2.50000000e-01, 1.25000000e-01,
        6.25000000e-02, 3.12500000e-02, 1.56250000e-02, 7.81250000e-03,
        3.90625000e-03, 1.95312500e-03, 9.76562500e-04, 4.88281250e-04,
        2.44140625e-04, 1.22070312e-04, 6.10351562e-05, 3.05175781e-05,
        1.52587891e-05, 7.62939453e-06, 3.81469727e-06, 1.90734863e-06,
        9.53674316e-07, 4.76837158e-07, 2.38418579e-07, 1.19209290e-07,
        5.96046448e-08],
       [5.00000000e-01, 1.00000000e+00, 5.00000000e-01, 2.50000000e-01,
        1.25000000e-01, 6.25000000e-02, 3.12500000e-02, 1.56250000e-02,
        7.81250000e-03, 3.90625000e-03, 1.95312500e-03, 9.76562500e-04,
        4.88281250e-04, 2.44140625e-04, 1.22070312e-04, 6.10351562e-05,
        3.05175781e-05, 1.52587891e-05, 7.62939453e-06, 3.81469727e-06,
        1.90734863e-06, 9.53674316e-07, 4.76837158e-07, 2.38418579e-07,
        1.19209290e-07],
       [2.50000000e-01, 5.00000000e-01, 1.00000000e+00, 5.00000000e-01,
        2.5000

In [19]:
x = np.random.multivariate_normal(np.zeros(dim_x), cov_mat, size=[n_obs, ])

In [20]:
beta_y = np.concatenate((1/np.arange(1,6), np.zeros(5),
                         1/np.arange(1,6), np.zeros(dim_x - 15)))
beta_d = np.concatenate((1/np.arange(1,11), np.zeros(dim_x - 10)))

beta_y

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [21]:
beta_d

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [22]:
b_y_sigma_b_y = np.dot(np.dot(cov_mat, beta_y), beta_y)
b_d_sigma_b_d = np.dot(np.dot(cov_mat, beta_d), beta_d)
b_y_sigma_b_y

5.30017361111111

In [23]:
b_d_sigma_b_d

2.9807134983623076